"""
Django settings for scitechjournals project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
import logging

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c4%#p(^sl-*d4g_7phm*+4h@@#bs@7=c$lb=6t84$jb7nd2m4h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scitechjournals.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scitechjournals.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': "scitechjournals",
        'USER': "postgres",
        'PASSWORD': "postgres",
        'HOST': "127.0.0.1",
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CELERY
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'

INSTALLED_APPS += [
    'django_celery_results',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'app/data_extraction')

# EMAIL (for Gmail example)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'journalsscitech@gmail.com'
EMAIL_HOST_PASSWORD = 'pgxd koyd bswx owze'  # use app-specific password
EMAIL_USE_TLS = True

USER_ROLE = {
    0: "Admin",
    1: "TL",
    2: "User",
}


EXTRACTION_TYPE = {
    0: "Pubmed New",
    1: "Pubmed Central",
    2: "Europe PMC",
    3: "Pubmed",
    4: "Koreamed"
}

PUBMED_NEW_EXTRACTION_FILE_TYPE = {
    "txt": "TXT",
}

PUBMED_CENTRAL_EXTRACTION_FILE_TYPE = {
    "txt": "TXT",
}

EUROPE_PMC_EXTRACTION_FILE_TYPE = {
    "ris": "RIS",
    "xml": "XML",
}

PUBMED_EXTRACTION_FILE_TYPE = {
    "txt": "TXT",
}


# LOG_DIR = BASE_DIR / "logs"
# LOG_DIR.mkdir(exist_ok=True)
#
# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#
#     "formatters": {
#         "verbose": {
#             "format": "%(asctime)s | %(levelname)-8s | %(name)s | %(module)s:%(lineno)d | %(process)d:%(threadName)s | %(message)s"
#         },
#         "server": {  # match Django's runserver style but richer
#             "format": "%(asctime)s | %(levelname)-8s | %(message)s"
#         },
#     },
#
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#         },
#         "file": {
#             "class": "logging.handlers.RotatingFileHandler",
#             "filename": str(LOG_DIR / "dev.log"),
#             "maxBytes": 10 * 1024 * 1024,  # 10 MB
#             "backupCount": 5,
#             "formatter": "verbose",
#             "encoding": "utf-8",
#         },
#     },
#
#     # send EVERYTHING to console + file
#     "root": {
#         "handlers": ["console", "file"],
#         "level": "DEBUG",
#     },
#
#     "loggers": {
#         # Core Django logs
#         "django": {
#             "handlers": ["console", "file"],
#             "level": "INFO",
#             "propagate": False,
#         },
#         "django.server": {           # runserver requests
#             "handlers": ["console", "file"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#         "django.request": {          # 4xx/5xx with tracebacks
#             "handlers": ["console", "file"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#         "django.security": {
#             "handlers": ["console", "file"],
#             "level": "WARNING",
#             "propagate": False,
#         },
#
#
# SQL queries (VERY noisy; include params + timings)
#         "django.db.backends": {
#             "handlers": ["console", "file"],
#             "level": "DEBUG",
#             "propagate": False,
#         },
#
#         # add your app(s) here if you want to tune separately
#         # "app": {"handlers": ["console", "file"], "level": "DEBUG", "propagate": False},
#     },
# }

KOREAMED_EXTRACTION_FILE_TYPE = {
    "txt": "TXT",
}