app_location: /
api_location: ""
output_location: out
app_build_command: npm run build
api_build_command: ""
routes:
  - route: /api/*
    methods: [GET, POST, PUT, DELETE]
    allowedRoles: [anonymous]
  - route: /*
    serve: /index.html
    statusCode: 200
navigationFallback:
  rewrite: /index.html
  exclude:
    - "/*.{png,jpg,gif,svg,css,js,json}"
    - "/api/*"
    - "/_next/*"
    - "/static/*"
responseOverrides:
  404:
    rewrite: /_not-found
    statusCode: 404
globalHeaders:
  content-security-policy: "default-src 'self' *.ariesview.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://*.ariesview.com https://*.azure.com"
  cache-control: "max-age=3600" 