# Generated by Django 5.0.1 on 2025-05-21 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_id', models.CharField(max_length=100, unique=True)),
                ('article_title', models.TextField(blank=True, null=True)),
                ('article_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('journal_id', models.CharField(max_length=100, unique=True)),
                ('journal_name', models.TextField(blank=True, null=True)),
                ('journal_link', models.TextField(blank=True, null=True)),
                ('total_articles', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.TextField(blank=True, max_length=1024, null=True)),
                ('site_link', models.TextField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0, help_text='0=active;1=inactive;2=delete')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=16, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('image', models.TextField(blank=True, max_length=1024, null=True)),
                ('user_type', models.IntegerField(default=0, help_text='0=Master Admin;1=Editor;2=App User;3=Author')),
                ('username', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('is_login', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0, help_text='0=active;1=inactive;2=delete')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.TextField(blank=True, null=True)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('author_email', models.TextField(blank=True, null=True)),
                ('article', models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, to='app.article', to_field='article_id')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, to='app.journal', to_field='journal_id'),
        ),
        migrations.AddField(
            model_name='journal',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='app.site'),
        ),
    ]
