# Generated by Django 5.0.1 on 2025-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
