# Generated by Django 5.0.1 on 2025-05-24 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_article_author_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='article_title',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(db_column='journal_id', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.journal', to_field='journal_id'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_month',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.site'),
        ),
        migrations.AlterField(
            model_name='author',
            name='article',
            field=models.ForeignKey(db_column='article_id', on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='app.article', to_field='article_id'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='total_articles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_link',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.SmallIntegerField(default=0, help_text='0=active;1=inactive;2=delete'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['article_id'], name='app_article_article_404113_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['journal'], name='app_article_journal_af30c1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_year'], name='app_article_publish_815520_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['author_email'], name='app_author_author__daff63_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['article'], name='app_author_article_50cd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['journal_id'], name='app_journal_journal_490d3b_idx'),
        ),
    ]
