# Generated by Django 5.0.1 on 2025-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_author_article_title_alter_article_article_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_info',
        ),
    ]
