# Generated by Django 5.0.1 on 2025-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_article_author_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='article_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
