# Generated by Django 5.0.1 on 2025-05-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_emails',
            field=models.IntegerField(default=0),
        ),
    ]
