# Generated by Django 5.0.1 on 2025-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_article_author_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('total_authors', models.IntegerField(default=0)),
                ('with_email', models.IntegerField(default=0)),
                ('without_email', models.IntegerField(default=0)),
            ],
        ),
    ]
