# Generated by Django 5.0.1 on 2025-06-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dataextraction_dataextractioninfo_article_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtractionArticle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_title', models.TextField(blank=True, null=True)),
                ('article_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('published_date', models.TextField(blank=True, null=True)),
                ('published_month', models.TextField(blank=True, max_length=15, null=True)),
                ('published_year', models.TextField(blank=True, null=True)),
                ('article_keywords', models.JSONField(blank=True, null=True)),
                ('is_email', models.BooleanField(default=False)),
                ('author_emails', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataExtractionAuthor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataExtractionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataExtractionInfo',
        ),
        migrations.RemoveField(
            model_name='dataextraction',
            name='total_authors',
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='extraction_file',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='extraction_groups',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='extraction_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='dataextractionarticle',
            index=models.Index(fields=['article_title'], name='app_dataext_article_faceec_idx'),
        ),
        migrations.AddIndex(
            model_name='dataextractionarticle',
            index=models.Index(fields=['published_year'], name='app_dataext_publish_c7dce9_idx'),
        ),
        migrations.AddField(
            model_name='dataextractionauthor',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_extraction_authors', to='app.dataextractionarticle'),
        ),
        migrations.AddIndex(
            model_name='dataextractionauthor',
            index=models.Index(fields=['author_email'], name='app_dataext_author__ee0027_idx'),
        ),
        migrations.AddIndex(
            model_name='dataextractionauthor',
            index=models.Index(fields=['article'], name='app_dataext_article_9239a7_idx'),
        ),
    ]
