# Generated by Django 5.0.1 on 2025-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_dataextractionarticle_dataextractionauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionauthor',
            name='author_affiliation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
