# Generated by Django 5.0.1 on 2025-06-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_dataextractionauthor_author_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionarticle',
            name='data_extraction',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_extraction', to='app.dataextraction'),
        ),
    ]
