# Generated by Django 5.0.1 on 2025-06-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_dataextractionarticle_data_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextraction',
            name='file_type',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
