# Generated by Django 5.0.1 on 2025-06-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_dataextraction_file_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataextraction',
            old_name='extraction_file',
            new_name='extraction_file_name',
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='extracted_by',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_extracted_by', to='app.users'),
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='output_excel_path',
            field=models.FilePathField(blank=True, match='.*\\.xlsx$', null=True, path='app/data_extraction', recursive=True),
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='total_records',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='dataextraction',
            name='total_unique_records',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dataextraction',
            name='extraction_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
