# Generated by Django 5.0.1 on 2025-06-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_extraction_file_dataextraction_extraction_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractionauthor',
            name='author_country',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
