# Generated by Django 5.0.1 on 2025-06-09 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_dataextractionauthor_author_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataextractionarticle',
            name='author_emails',
        ),
        migrations.RemoveField(
            model_name='dataextractionarticle',
            name='is_email',
        ),
        migrations.RemoveField(
            model_name='dataextractionarticle',
            name='published_month',
        ),
    ]
