# Generated by Django 5.0.1 on 2025-08-06 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_backuplog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataextractiongroup',
            name='user',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_extraction_group_user', to='app.users'),
        ),
    ]
