# Generated by Django 5.0.1 on 2025-08-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_dataextractiongroup_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDataExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('drive_link', models.URLField(blank=True)),
            ],
        ),
    ]
